osx_image: xcode8.3
language: objective-c
rvm: 2.4.1
cache:
  - bundler
  - cocoapods
install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - travis_wait 30 bundle exec pod repo update --silent
  - travis_wait 30 bundle exec pod install
script:
  - travis_retry bundle exec rake ci
  - travis_wait 50 bundle exec rake lint
branches:
  only:
    - master
    - development
    - /^release/
