language: objective-c
before_install:
    - brew update
    - brew uninstall xctool
    - brew install xctool
install: bundle exec pod install
script:
    - rake server:start test test:building_without_core_data
    
