osx_image: xcode8.3
language: objective-c
rvm: 2.4.1
cache:
  - bundler
  - cocoapods
before_install:
  - brew outdated xctool || brew upgrade xctool
script:
  - bundle exec rake ci
branches:
  only:
    - master
    - development
    - /^release/
